# Generated by Django 5.0.1 on 2024-01-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("date", models.DateField(auto_now=True)),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
            ],
        ),
    ]
